# Generated by Django 4.0.5 on 2022-06-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        ('characteristics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='animal',
            field=models.ManyToManyField(related_name='characteristic', to='animals.animal'),
        ),
    ]
