# Generated by Django 4.0.5 on 2022-06-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0002_characteristic_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristic',
            name='animal',
        ),
    ]
