# Generated by Django 4.0.5 on 2022-06-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0003_remove_characteristic_animal'),
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='characteristic',
            field=models.ManyToManyField(related_name='animals', to='characteristics.characteristic'),
        ),
    ]
