# Generated by Django 4.0.5 on 2022-06-26 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_characteristic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='characteristic',
            new_name='characteristics',
        ),
    ]
