# Generated by Django 4.0.5 on 2022-06-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='scientific_name',
            field=models.CharField(max_length=50),
        ),
    ]
